### ISSUE TITLE
Latest Build of cosmos not allowing player to move after turning on movement modules

### ISSUE THREAD

**Issue by CynicalMuffin** [linustouchtips/cosmos#20]
so i got cosmos latest build from its src and im not sure why but on singleplayer and mutliplayer im unable to move at all after turning on movement modules

So after restarting the client with no modules enabled i could move around but the moment i turned on any module in movement 
(in crystalpvp.cc) i got teleported to the server spawnpoint

**Comment by HausemasterIssue** [comment]
yeah same happens to me

**Comment by linustouchtips** [comment]
don't use cosmos from the src, much of the client will be untested or unfinished. use the build in the releases tab.

**Comment by linustouchtips** [comment]
well it's the latest tested build

**Comment by CynicalMuffin** [comment]
thanks for clarifying!

**Comment by HausemasterIssue** [comment]
me :gorilla: me do not has IQ
