### ISSUE TITLE
bring back the old gui

### ISSUE THREAD

**Issue by master7720** [linustouchtips/cosmos#24]
the new gui is dog shit you cant even config any modules pls bring back the old gui everyone loved it

**Comment by HausemasterIssue** [comment]
the new gui is wip :/

**Comment by linustouchtips** [comment]
you can config on the new gui

**Comment by master7720** [comment]
ok my bad you fixed the config problem but still bring back the old gui the new one sucks ass

**Comment by linustouchtips** [comment]
i don't plan on bringing back the old gui

**Comment by linustouchtips** [comment]
yes.
